# Generated by Django 2.2.14 on 2020-07-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbtemp_app', '0002_auto_20200726_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentupload',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('uploaded', 'uploaded')], max_length=20),
        ),
    ]
