# Generated by Django 2.2.14 on 2020-07-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbtemp_app', '0004_auto_20200726_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='files',
            field=models.FileField(upload_to='activities'),
        ),
        migrations.AlterField(
            model_name='studentupload',
            name='files',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
